### ISSUE TITLE
Issue with '<' character

### ISSUE THREAD

**Issue by jtbandes** [NSHipster/clangwarnings.com#15]
This is wrong; it looks like the `<`s are being eaten:

https://github.com/NSHipster/clangwarnings.com/blob/02166494d462f91776ed28e77e24db581725c588/_data/lex.yml#L14-L16

The [actual message](https://github.com/llvm-mirror/clang/blob/e72aad6948944d73af10ad4246a31793f7ae43f0/include/clang/Basic/DiagnosticLexKinds.td#L30-L32) is:

```
def warn_cxx98_compat_less_colon_colon : Warning<
  "'<::' is treated as digraph '<:' (aka '[') followed by ':' in C++98">,
  InGroup<CXX98Compat>, DefaultIgnore;
```

(As a side note, have you seen https://clang.llvm.org/docs/DiagnosticsReference.html? They've got some interesting layout ideas with expanding the `%select`s vertically.)

**Comment by mattt** [comment]
Hi @jtbandes. Thanks for pointing this out.

I actually hadn't seen Clang's Diagnostics Reference docs. They [appear to have been added](https://github.com/androm3da/clang-doc/commit/89f2f0d1857f59e6c3625b0aaee69b76a74722cb#diff-b1be48583698a8302bac6ec5266be7ed) a few years after I originally made this.

To be honest, the existence of that document effectively deprecates this project. It's much better to get the information direct from the source, and this has more and better information overall. I'll reach out to the Clang team to see if they'd like to coordinate on this.

**Comment by mattt** [comment]
Thanks again for pointing out the official Clang docs. I just switched over the DNS to redirect [clangwarnings.com](https://clangwarnings.com) to that page, and am archiving this project.
