### ISSUE TITLE
Work-friendly mirror

### ISSUE THREAD

**Issue by nlutsenko** [NSHipster/clangwarnings.com#8]
Following the convention of `https://goshdarnblocksyntax.com` it might be a good idea to create a work-friendly mirror for this. Not sure on how big of an impact that would be, tbh, but would gladly donate money for a domain name just to see `goshdarnclangwarnings.com` live :)

**Comment by bchretien** [comment]
:+1: Because sometimes this happens:

```txt
Web Page Blocked
Access to the web page you were trying to visit has been blocked in accordance with
company policy. Please contact your system administrator if you believe this is in error.                                                        
URL: fuckingclangwarnings.com/
Category: adult-and-pornography
```

**Comment by quinntaylor** [comment]
Please. Even sending the current URL to people in a professional setting can be offensive or come across as harassment.

**Comment by NiklasRosenstein** [comment]
Since this repository hasn't been updated in a long while, I've created a fork here that contains all open suggestions in this repository to this date.

https://github.com/NiklasRosenstein/clangwarnings

Not sure how many people will use this fork, so I didn't feel the need of getting a new domain name yet, but for now it's accessible via http://bit.ly/clangwarn which will redirect to the GitHub.io page at https://niklasrosenstein.github.io/clangwarnings/.

**Comment by Coeur** [comment]
@NiklasRosenstein may you activate "issues" on your fork?

**Comment by NiklasRosenstein** [comment]
@Coeur I just did

**Comment by mattt** [comment]
The unfortunate naming of this project been bugging me for a long time, and it's a huge relief to now finally be able to do something about it.

I acknowledge that the original naming was in poor taste, and created an unnecessary boundary to accessing useful information for no reason in particular. I sincerely apologize to you, @nlutsenko, @bchretien, @quinntaylor, and everyone else who has been inconvenienced by this over the years. 

Thank you, @nlutsenko, for stepping up and offering a work-friendly fork of the project in the meantime.

So here's the good news: this project has been renamed to "[clangwarnings.com](https://clangwarnings.com)", and any remaining profanity has been removed (e.g. the footer now links to http://goshdarnblocksyntax.com). The old URLs will be updated to redirect to this new domain (this should take effect in the next 24 hours).

If anyone has any additional concerns not addressed by these changes, please let me know. Thank you all for your patience and contributions.
